spring:
  profiles:
    active: local


springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    display-request-duration: true  # 요청 실행 시간 표시
    # groups-order: DESC
    operationsSorter: method  # CRUD 메소드 순으로 정렬
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: true
#  group-configs:
#    - group: stores
#      paths-to-match: /store/**
